import Head from "next/head";
import { useRouter } from "next/navigation";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>MotionVerse - The Ultimate Notion Widget Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <p>
            hello does this work
          </p>
          <button
            onClick={() => router.push("/build/stock")}
          >
            Dashboard
          </button>
        </div>
      </main>
    </>
  );
}
